import {manifestId} from './manifest.js';
export const types = ['concept','module','question','source','hypothesis','experiment','evidence','decision','milestone'];
export const verbs = {contains:['concept','module'],concerns:['question','module'],investigates:['hypothesis','question'],tests:['experiment','hypothesis'],informs:['source','question'],supports:['evidence','decision'],requires:['milestone','experiment'],resolves:['decision','question']};
const rec=(id,type,title,summary,detail,x,y,extra={})=>({id,type,title,summary,detail,x,y,claim:type==='concept'||type==='module'?'concept':type==='question'?'unknown':'proposal',locked:true,...extra});
export const seedRecords=[
rec('vision','concept','Recoverable flight','One ambitious idea. Many questions worth exploring.','A modular vehicle, deployable wings, and a recoverable payload. This board turns the original idea into connected questions, experiments, and decisions. Original aspiration: 7–8 ft long, 1 ft body diameter, 3–4 ft total deployed wingspan including the body. No vehicle has been built or flown.',430,80),
rec('nose','module','01 / Recovery payload','A detachable nose. A different way down.','Cone payload with an altimeter, other hardware, and two fins. Intended to detach and glide; the cone is not a validated glider. Lift, balance, control, and recovery for every separated piece remain open.',1020,60,{source:'vision-source'}),
rec('wing','module','02 / Deployable wings','Stow within. Open possibilities.','Two wings stow inside the cylindrical middle module. A motor, gear, and axle region illustrates the idea, not a validated mechanism. Deployment and self-orientation are separate questions. The original fuel-body description does not select propulsion.',1020,290,{source:'vision-source'}),
rec('aft','module','03 / Propulsion concept','Jet-inspired form. Architecture still open.','Two small aft fins and fighter-jet-inspired thruster styling. A rocket motor and a jet turbine are different architectures. No engine, motor, or final flight geometry is selected.',1020,520,{source:'vision-source'}),
rec('pack','question','How does it all fit?','Internal wings, hardware, and room to move.','Can two wings, their actuation hardware, wiring, and recovery equipment fit inside the body without interference? Actual dimensions, clearances, and a measured packaging mockup are needed.',60,95,{source:'spec-source'}),
rec('recover','question','What comes back?','Every separated piece needs a plan.','Which pieces separate? How does each descend, get tracked, and get recovered? A detachable nose does not solve recovery for the other modules.',60,335,{source:'spec-source'}),
rec('hyp','hypothesis','An internal folding arrangement','A packaging hypothesis, ready to investigate.','An internal segmented arrangement may fit. Actual component dimensions, mass, and clearances are unknown. The visual model depicts discrete poses; it does not establish a continuous deployment path.',60,780,{locked:false}),
rec('test','experiment','Build an inert packaging mockup','A proposed first step, before flight hardware.','Compare the occupied volumes and record interference in an inert mockup. Criterion: not set, requires mechanical review. Authorization: not reviewed. Article revision: not established. Outcome: no test performed.',405,780,{locked:false}),
rec('decision','decision','Keep packaging open','Let measured evidence decide.','Proposed: keep the packaging question unresolved until an inert mockup provides measured dimensions and a reviewer-set criterion. No physical architecture is accepted.',750,780,{locked:false}),
rec('baseline','concept','Start with independent articles','A proposed path to the larger idea.','C0: inert wing mechanism. C1: smaller conventional rocket with certified commercial propulsion and established recovery/tracking. C2: separate lightweight glider. This is a recommendation, not the team’s accepted architecture.',60,1090,{claim:'proposal'}),
rec('goals','question','What should we prove first?','Recovery · mechanisms · measurement · speed','Candidates: repeatable recovery, telemetry/video replay, inert deployment and separate glider, held-out prediction, and a separately reviewed Mach 1 goal. Optional drone recovery and simulator development stay open. No priority order is selected.',405,1090),
rec('gate','milestone','G0 / Define the mission','Open · scope, budget, mentor, and test access','G0 requires advisor agreement to scope, owned unknowns, and test criteria. G1: independent bench/model evidence. G2: independent flight articles. G3: integration decision. G4: approved integration and reuse evidence. None is completed.',750,1090),
rec('vision-source','source','Captured project vision','The idea, in its own terms.','Repository user-vision snapshot. Original whiteboard and spoken descriptions are context, not engineering approval. Personal names and the source photograph are not included.',60,1390,{claim:'concept',url:'/sources/USER-VISION.md'}),
rec('spec-source','source','System requirements','A source for questions and interfaces.','Preliminary requirements, not flight approval. Every separated piece requires a recovery plan; deployment is distinct from flight control; evidence must identify its type.',405,1390,{url:'/sources/SYSTEM-SPEC.md'}),
rec('evidence','evidence','Evidence starts with provenance','Documentation exists. Flight evidence does not.','This record refers to the written preliminary specification only. It is documentary context, not measured or simulated vehicle evidence. No packaging test, flight log, or aerodynamic result exists.',750,1390,{claim:'unknown',source:'spec-source'}),
rec('guidance','question','What does “self-orient” mean?','Deployment, navigation, guidance, control.','Navigation estimates motion. Guidance describes a desired state or path. Control changes behavior toward it. Wing deployment changes configuration. Define the desired independent-aircraft behavior before selecting software or actuators; powered-flight guidance is outside this workspace.',1110,1090),
rec('drone','question','Could a drone help recovery?','Carried payload or a separate search tool?','A carried drone adds mass, power, packaging, release/transition questions, and aircraft-operation review. A separate search drone avoids carriage but does not replace tracking. Both remain optional research, not authorized operations.',1110,1390),
rec('sim','question','Extend, fork, or build?','Simulation is a separate workstream.','Open-source tools are candidates for bounded evaluation. No simulator route is selected or executed. Verify model assumptions and compare with independent evidence before trusting a result. A rendered pose is not a solver output.',1110,780)
];
export const seedEdges=[['vision','nose','contains'],['vision','wing','contains'],['vision','aft','contains'],['pack','wing','concerns'],['recover','nose','concerns'],['hyp','pack','investigates'],['test','hyp','tests'],['decision','pack','resolves'],['spec-source','pack','informs'],['evidence','decision','supports']].map((e,i)=>({id:`edge-${i}`,from:e[0],to:e[1],verb:e[2]}));
export const newProject=()=>({schema:1,manifest:manifestId,revision:0,records:structuredClone(seedRecords),edges:structuredClone(seedEdges),view:{x:0,y:0,z:1},story:['vision','wing','test','baseline','gate']});
export function validateProject(p){
 if(!p||p.schema!==1)throw Error('Unsupported project version. Your current board is unchanged.');
 if(!Array.isArray(p.records)||p.records.length>300||!Array.isArray(p.edges)||p.edges.length>1000)throw Error('Invalid project size.');
 const ids=new Set();
 for(const r of p.records){if(!r||typeof r.id!=='string'||!/^[a-zA-Z0-9-]{1,90}$/.test(r.id)||ids.has(r.id)||!types.includes(r.type))throw Error('Invalid or duplicate record.'); ids.add(r.id); for(const k of ['title','summary','detail'])if(typeof r[k]!=='string'||r[k].length>20000)throw Error('Invalid record text.'); if(!Number.isFinite(r.x)||!Number.isFinite(r.y)||Math.abs(r.x)>10000||Math.abs(r.y)>10000)throw Error('Invalid card position.'); if(r.url&&!/^https?:\/\//.test(r.url)&&!/^\/sources\/[A-Z-]+\.md$/.test(r.url))throw Error('Unsupported source URL.');if(!['concept','proposal','estimated','simulated','measured','unknown'].includes(r.claim))throw Error('Invalid claim class.'); }
 const edgeIds=new Set();for(const e of p.edges){const pair=verbs[e.verb]; if(!e.id||edgeIds.has(e.id)||!ids.has(e.from)||!ids.has(e.to)||!pair||p.records.find(r=>r.id===e.from).type!==pair[0]||p.records.find(r=>r.id===e.to).type!==pair[1])throw Error('Invalid relationship.');edgeIds.add(e.id);}
 for(const r of p.records)if(r.source&&!ids.has(r.source))throw Error('Missing source record.');
 for(const original of seedRecords){const r=p.records.find(r=>r.id===original.id);if(!r)throw Error('A source record is missing.');if(!original.locked&&(r.locked||r.claim!=='proposal'||r.type!==original.type))throw Error('Starter proposals cannot be promoted.');if(original.locked)for(const k of ['type','title','summary','detail','claim','locked','url','source'])if(r[k]!==original[k])throw Error('Canonical source records cannot be overwritten.');}
 for(const r of p.records)if(!seedRecords.some(s=>s.id===r.id)&&(!['question','hypothesis','experiment','decision'].includes(r.type)||r.locked||r.claim!=='proposal'))throw Error('New records must be local proposals.');
 if(!p.view||!['x','y','z'].every(k=>Number.isFinite(p.view[k]))||p.view.z<.25||p.view.z>1.6)throw Error('Invalid viewport.');
 if(!Array.isArray(p.story)||p.story.length>5||p.story.some(id=>!ids.has(id)))throw Error('Invalid story references.');
 if(!Number.isSafeInteger(p.revision)||p.revision<0||typeof p.manifest!=='string')throw Error('Invalid project metadata.');return p;
}
export function saveProject(storage,key,project,expected){const raw=storage.getItem(key);if((raw===null&&expected!==0)||(raw&&JSON.parse(raw).revision!==expected))throw Error('Another tab changed this board. Export your copy, then reload.'); const next={...project,revision:expected+1};storage.setItem(key,JSON.stringify(next));return next;}

export function recoverProject(storage,key,unreadableRaw){
 const current=storage.getItem(key);
 if(current!==unreadableRaw)throw Error('The saved data changed. Reload before recovering.');
 if(current!==null)storage.setItem(key+':recovery',current);
 const fresh={...newProject(),revision:1};
 storage.setItem(key,JSON.stringify(fresh));
 return fresh;
}
