import test from 'node:test';
import assert from 'node:assert/strict';
import {newProject,recoverProject,saveProject,validateProject} from '../src/data.js';
const fixture=()=>{const values=new Map([['board','{broken-data']]);return {getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};};
test('recovery saves original bytes before creating a valid fresh board',()=>{const s=fixture();const p=recoverProject(s,'board','{broken-data');assert.equal(s.getItem('board:recovery'),'{broken-data');assert.deepEqual(validateProject(JSON.parse(s.getItem('board'))),p);});
test('recovery refuses to overwrite data changed after observation',()=>{const s=fixture();s.setItem('board','newer');assert.throws(()=>recoverProject(s,'board','{broken-data'),/changed/);assert.equal(s.getItem('board'),'newer');});
test('failure to store recovery copy leaves original untouched',()=>{const s=fixture();assert.throws(()=>recoverProject({getItem:s.getItem,setItem:()=>{throw Error('quota');}},'board','{broken-data'));assert.equal(s.getItem('board'),'{broken-data');});
test('invalid save candidates never replace a valid stored board',()=>{const s={values:new Map(),getItem(k){return this.values.get(k)??null;},setItem(k,v){this.values.set(k,v);}};const original=saveProject(s,'board',newProject(),0),before=s.getItem('board');for(const mutate of [p=>p.view.z=.24,p=>p.records.find(r=>r.id==='hyp').x=10001]){const candidate=structuredClone(original);mutate(candidate);const caller=JSON.stringify(candidate);assert.throws(()=>saveProject(s,'board',candidate,1),/Invalid viewport|Invalid card position/);assert.equal(s.getItem('board'),before);assert.equal(JSON.stringify(candidate),caller);}});
test('valid saves increment revisions and retain conflict protection',()=>{const s={values:new Map(),getItem(k){return this.values.get(k)??null;},setItem(k,v){this.values.set(k,v);}};const first=saveProject(s,'board',newProject(),0),candidate=structuredClone(first);candidate.records.find(r=>r.id==='hyp').x=75;const second=saveProject(s,'board',candidate,1);assert.equal(second.revision,2);assert.equal(JSON.parse(s.getItem('board')).records.find(r=>r.id==='hyp').x,75);assert.throws(()=>saveProject(s,'board',candidate,1),/Another tab/);});
